version: '3'

services:
  web:
    build: .
    ports:
      - "5101:5101"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flask_project
