"""empty message

Revision ID: 2110194ad824
Revises: 91a7c36475a7
Create Date: 2023-10-20 00:42:45.356792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2110194ad824'
down_revision = '91a7c36475a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=False))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
